# nixpacks.toml - Nixpacks config for Laravel

[phases.install]
cmds = ["COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs"]

[env]
COMPOSER_ALLOW_SUPERUSER = "1"
